---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grappa-db
  namespace: openeo
spec:
  encryptedData:
    password: AgAvJSRbyWGHldTuWlc1jeAPVZdfBKRdeg+jFSQEaUIgT5zusLV3gHe80arql++K1tI5XjrPOYD2vYa/zPnAvlEQ491ajJQKjtWT317+fXHbM0Fu2PqGBGvT+7NxVd0vnoAtmh0SxYAUSFgqBQxjvlFDFt3ceIoVYJBBwlD+zm+BXEO/SqEJLRunwmLuNNuZtBt/h8s1aJPkoeui7ymdlPemkHtRYgB1qT0yaVwbYIzt7kYc2GVsYDMwZ7mlcypMq/sULjcb9zglK1DiVV0YS3ZMkwXuoUP65PNtjBSfBuvQfbOwMSQbFiHs4DlmawPbgDpOCEgojDMs5pB1LOKgY1DYzbV8de3LBg8NgNLOP6TbQmOv8KcAtKuSN2iPgW3GZg+yzbJIB7axE/rfqdu9W+sxwZDslMpc0Q4NN5GrMqdtevmSL3YgsHIHrnjP7LLcDYwURiPFHF8Vv0som9CKXhPJYEcb4KOt2xA4sXt1eHkgeS0jnFwUQwaMfZhi7qZ7m2x9G6fcrPiv9U+hO6VHmlG6DePbc8uEfEOwh9JaD6S6xGa3J1b9akUUbQB4zVRc/i/nivHEOklBKMzV5iZX0tCi+45bP1l2CVd71WZLI22eWNKZFbYIczvLdk0YyzuP9+KCdL5G98F6aJxCUzkmzICu2rVOCNlzsTUtJICYpAT2cbChBz6YWXGHEewrCQgLf4cN1xVu02j+OrHtB1vfj6P0imhXZ5CVHe990G4zM6k=
    url: AgA7q4XD3ppi0w0icOd/zikfvSpTxBukvX0o8gpuUJHKwbzUKFXXgdvjllurcJiiYMlZ00rr+WyI4FKSo/q8Ae9L4bMRhJ876CeMjLbdI0BZQwb48aapRYjo5UmCL/Ypf+ImUycXj28a2qx4kcCuqWO4NIAPZVnBkTi7tGRO0hGiDE9RfIuS4DkdgNb87vuTm5JNTMCGutlloa9sfsywVNJJlk841Hs+7o9lFcnv/m6CEKhNCXm285Z5bupCCXkQAHj/vzl41npSvf7VjfYNs4RlkB0OSlza43iXk/sIgdX2VqsoBOpJDk7/tNGYmPE/9jBVJsMEN0lFqiDWJKNEXXdsB7AN6uKv/WlT49B5q+pFOIZ2+wKlT90tmJPSr6L+1q+zdRpWDXQgZal3NjOBDkpFS/kq7bRcEUr9EE8uo9hGV2fOLBe5GNSkhVjknZ6K5Rbi2IXYwckfB3Jp+MND0Y2ooeg2tbWX/14Ng8dT9iJDEu/ssf5SFi+cZRGjBWHsSOR27IoJuevFIN6/pbu6v/actHY1Wjchk/jCuaNhN+GmClnB/GRXRoBudLiEiJXZDqhx6L4ludPyEXdDl3mn0aKj3KI+U+N2ko+XabyLRRjWRgEv+jdgqpChYe5uRRAH6qQTeA2kVGnxMmotayjefLnK8zaVdhnJFTzl5P6B5suykjHMuvbSt6z3yfaEVk8ozxG6Aa7IlKrG1qHCBahriqCYME4caU82TGGp1MpJZ2gDAwl23RfmEAmXpxMlAhyNMibfSGEXyh1effdIc8pEkvqRHMO/btI=
  template:
    metadata:
      name: grappa-db
      namespace: openeo
    type: Opaque
