apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grappa-results
    namespace: openeo
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 5Gi
