apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-data
    namespace: openeo
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 8Gi
