---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientID: AgA8u5FROxpPRDZdoDT8XpvQnZRB7OPGwfFDxPRVEe9CYDb/d5WqzBF3Vd8mm9UjcMTsw0Y2upka6D1O9OLdp7DWxxWBPJU6ud65XifQiEP4rhf0ZWU2A7cWEoDpkFGoEGcj3Hih91wqMqNq0pQr3V73aUNzKVocI6owKY5JnmEAfp0CrQzOw2qCRs7jCk64+ooUgf6pvOtvma0oGnwSTdk0XN5h0py2TxcJq4GT73mZNQ7lEWBT5MAie59H4pug7dnAZBKfxVGcKbowQv3/X4fc05YWXCEzmR0DRI2ZFkEjAPQpsahacYTAHwte116tCv52H1FsXJ6mB8hQOOfOMfVB057XSa7ZPL9PlwZBKGjWx2IbF+JmbD9hPIQVZPicgTwjmYNaN8GnorKPzCIBhVZ9hW4zjol4FbqqNwcUoibsVwq5sxA4/nbBvNr62e3weQYVAg6vQ67AItV3WT/Mxi296/H2Ngc/bJA7kMYDBGRpOO9bT2auE+l0maBpvZtbVM3O33SgQ7PMBK5CILOnCwpiCfqu6mJ0EjS1NuJnwqbJcN6pDp86thyfYXm2vDGhEI6hKUbxWsJin4JleaXrhCasNcFYsewk0DI8UvVBnceqoAAq2RdWUH2vVPd7aQsvbnYYfT+Wud+2Vc3NUxDnhKkRSxDIWN5r9si6akUNt0lURxmmvWUIEJLFeNGYPmR8YL4CGvQRvRb3wezXbMFszpOV6g6/mQ==
    dex.github.clientSecret: AgAY5cq91BqzDUBtOu4IS+BrM4XbInvVX5qkoXFUv2rcF6UqS9ZYGEvmU3oaBOvon6cauTMiK+xW+tnyckphakpPizb/VgxJ+j8DW+r/++fnqXoI5X1uLMxZprt+7E240FbV1hUkODPXrKf/uCIfEYMXLi41bzj8h/vzoEHo9zY8Ej2ml5OebruomtoXU4wMQ3zDm0H6X+wtundKSKvDuEgJajqD45SiCkqKkt7ARBdzmgW3bXeS21aoeYAM/5ZOH5WxN0nG4g52qoTG4JhUcgNt3H8BUPtX0xclCz2fGjvhAE4PKUKGvXtpFdTQ/186q9bBXtqvSlNZF/+Y0h5GtVosz+1YjdgG6woKHa23gfPxi77reeZzlBXNDYDUJfKxEJ2nBeYpLMV5rMJ3c4GqmrFl6o/i0U5DhT3ov9oWMY6k/uk214TyrYzEsk6+qlX3WIeMOj16rRtPM4MmvpO13SOU8J4tmg0/bXRNFUemaHbO1532qzogGmfdYkavf0XP39+IwK/pzGlB7xzFOCmjQlBYvfKscj3/dHqBCcoqm379Sqk5q1uzEd4I9LUNQYGSO5NmPMj7mrfI+G3+xsVJIiRszar6n5RlHPAfHZfPUMMHWfCVwUeiPyvzHVZ2QdJQ78UbCqfL7HcUzB4xONalA5Lv3srNvYeLhBJdNaFbaqJKdD2INHbseAUOlO5d/qjwAsPPyEZAoWvujrI9zH0xMrcAmaYehJnncofF/5obpi7a9ub0up0xJHQU
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: github-oauth
      namespace: argocd
